version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # Utiliser le port 8080
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Variables MongoDB
      - MONGODB_URI=${MONGODB_URI}
      - DB_NAME=${DB_NAME}
      # Variables SendGrid
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - FROM_EMAIL=${FROM_EMAIL}
      # Autres variables selon vos besoins
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    volumes:
      # Pour le développement
      - .:/app
      - /app/node_modules
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
